config/routes.rb
Rails.application.routes.draw do

  get 'directions/index'

  get 'directions/show'

  get 'directions/new'

  get 'directions/create'

  get 'directions/update'

  get 'directions/destroy'

  get 'regions/index'

  get 'regions/show'

  get 'regions/new'

  get 'regions/edit'

  get 'regions/search'

  get 'regions/search_result'

  get 'wineries/index'

  get 'wineries/show'

  get 'wineries/new'

  get 'wineries/edit'

  get 'wineries/search'

  get 'wineries/search_results'

  get 'wineries/index'

  get 'wineries/show'

  get 'wineries/new'

  get 'wineries/edit'

  # get 'wineries/search'

  # get 'wineries/search_results'

  root "pages#home"
  get "/home" => "pages#home"
  get "/about" => "pages#about"

  get "/wineries/searches" => "wineries#searches", :as => "search_wine"
  get "/wineries/search" => "wineries#search", :as => "search_wineries"
  get "/regions/search" => "regions#search", :as => "search_regions"
  get "/regions/search" => "region#search", :as => "search_region"
  get "/travellers/search_results" => "travellers#search_results", :as => "search_traveller"
  get "/travellers/additional_info" => "travellers#additional_info", :as => "additional_info_traveller"
  get "/travellers/edit" => "travellers#edit", :as => "edit_traveller"
  resources :travellers, :except =>[:edit]
  #Creates the CRUD urls for me (but ignoring EDIT)

  resources :wineries, :regions
  # this will allow you to have links and paths to wineries and regions

  get "/login" => "session#new", :as => "login"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"


end

app/models/traveller.rb
# == Schema Information
#
# Table name: travellers
#
#  id              :integer          not null, primary key
#  first_name      :text
#  last_name       :text
#  email           :string
#  image           :text
#  dob             :date
#  password_digest :text
#  admin           :boolean          default(FALSE)
#  phone           :string
#  city            :text
#  country         :text
#  lat             :float
#  long            :float
#  fav_winery      :text
#  fav_region      :text
#  fav_variety     :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  location        :string
#

class Traveller < ActiveRecord::Base
  has_secure_password
  has_and_belongs_to_many :wineries
  has_many :regions, :through => :wineries
  geocoded_by :location, :latitude  => :lat, :longitude => :long # ActiveRecord
  after_validation :geocode
end

app/controllers/travellers_controller.rb
class TravellersController < ApplicationController
  before_action :authorise, :only => [:edit, :update]

  def landing
  end

  def index
    @travellers = Traveller.all
  end

  def show
    @traveller = Traveller.find_by :id => params[:id]
  end

  def new
    @traveller = Traveller.new
  end

  def create
    @traveller = Traveller.new traveller_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @traveller.image = req['public_id']
    end
    if @traveller.save
      session[:traveller_id] = @traveller.id
      # redirect_to traveller_path( @traveller )
      redirect_to additional_info_traveller_path
    else
      render :new
    end
  end

  def additional_info
    @traveller = @current_traveller
    # if @traveller.save
    #   session[:traveller_id] =@traveller.id
    #   redirect_to traveller_path( @traveller )
    # else
    #   render :new
    # end
  end

  def edit
    # @traveller = Traveller.find_by :id => params[:id]
    @traveller = @current_traveller
  end

  def update
      @traveller = @current_traveller
      if params[:file].present?
        req = Cloudinary::Uploader.upload(params[:file])
        @traveller.image = req['public_id']
      end
      @traveller.assign_attributes( traveller_params )
      if @traveller.save
        redirect_to @traveller
      else
        render :edit
      end
    end

    def destroy
      traveller = @current_traveller
      traveller.destroy
      redirect_to root_path()
    end

    def search
    end

    def search_results
    end

    private
      def traveller_params
        params.require(:traveller).permit(:email, :first_name, :last_name, :password, :password_confirmation, :image, :dob, :phone, :city, :country, :fav_winery, :fav_region, :location)
      end

      def authorise
        unless @current_traveller.present?
        flash[:error] = "You need to be logged in to do that"
        redirect_to login_path()
        end
        # If there is no @current_traveller variable defined
          # Create a temporary error message
          # Redirect them to the login page
      end
end

app/helpers/travellers_helper.rb
module TravellersHelper
end

app/views/travellers/_additionalinfo.html.erb
<div class="formtext">
  <div class="formtext-background"></div>
 <%= form_for(@traveller, :html => {:multipart => true}) do |f| %>

<p>
  <%= f.label :image %>
  <%= f.cl_image_upload :image, :required => false %>
</p>

<p>
  <%= f.label :dob %>
  <%= f.date_field :dob, :required => false %>
</p>

<p>
  <%= f.label :phone %>
  <%= f.text_field :phone, :required => false %>
</p>

<p>
  <%= f.label :city %>
  <%= f.text_field :city, :required => false %>
</p>

<p>
  <%= f.label :country %>
  <%= f.text_field :country, :required => false %>
</p>

<!-- <p>
  <%= f.label :location %>
  <%= f.text_field :location, :required => true %>
</p> -->

<p>
  <%= f.label :fav_winery %>
  <%= f.text_field :fav_winery, :required => false %>
</p>

<p>
  <%= f.label :fav_region %>
  <%= f.text_field :fav_region, :required => false %>
</p>

<%= f.submit %>
<% end %>
</div>

app/views/travellers/_editform.html.erb
<div class="formtext">
  <div class="formtext-background"></div>

<%= form_for @traveller, :html => { :multipart => true } do |f| %>

<p>
  <%= cl_image_tag(@traveller.image, :transformation=>[
  {:width=>200, :height=>200, :gravity=>"face", :radius=>"max", :crop=>"crop"},
  {:width=>100}
  ])%>
<br>
 <%= f.label :image %>
 <%= f.cl_image_upload :image, :required => false %>
</p>

<p>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, :required => true %>
</p>

<p>
  <%= f.label :last_name %>
  <%= f.text_field :last_name, :required => true %>
</p>

<p>
  <%= f.label :email %>
  <%= f.email_field :email, :required => true %>
</p>

<p>
  <%= f.label :password %>
  <%= f.password_field :password, :required => true %>
</p>

<p>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :required => true %>
</p>


<p>
 <%= f.label :dob %>
 <%= f.date_field :dob, :required => false %>
</p>

<p>
 <%= f.label :phone %>
 <%= f.text_field :phone, :required => false %>
</p>

<p>
 <%= f.label :city %>
 <%= f.text_field :city, :required => false %>
</p>

<p>
 <%= f.label :country %>
 <%= f.text_field :country, :required => false %>
</p>

<!-- <p>
 <%= f.label :location %>
 <%= f.text_field :location, :required => true %>
</p> -->

<p>
 <%= f.label :fav_winery %>
 <%= f.text_field :fav_winery, :required => false %>
</p>

<p>
 <%= f.label :fav_region %>
 <%= f.text_field :fav_region, :required => false %>
</p>

<%= f.submit %>
<% end %>
</div>

app/views/travellers/_form.html.erb
<!-- If the traveller has any error messages  -->
  <!-- Iterate through all of them -->
    <!-- Print out the messages -->
<% unless @traveller.errors.full_messages.empty? %>
<ul>
  <!-- Every error message printed out as a list item -->
  <%= @traveller.errors.full_messages.each do |error| %>
  <li>
    <%= error %>
  </li>
 <% end %>
</ul>
<% end %>
<div class="formtext">
  <div class="formtext-background"></div>
<%= form_for @traveller, :url => "/travellers/#{@traveller.id}", :html => { :multipart => true } do |f| %>

<p>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, :required => true %>
</p>

<p>
  <%= f.label :last_name %>
  <%= f.text_field :last_name, :required => true %>
</p>

<p>
  <%= f.label :email %>
  <%= f.email_field :email, :required => true %>
</p>

<p>
  <%= f.label :password %>
  <%= f.password_field :password, :required => true %>
</p>

<p>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :required => true %>
</p>


<%= f.submit %>
<% end %>
</div>

app/views/travellers/_searchform.html.erb
<%= form_for(@winery, :html => {:multipart => true}) do |f| %>

<p>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>
</p>

<p>
  <%= f.label :winery_image %>
  <%= f.cl_image_upload :winery_image, :required => true %>
</p>

app/views/travellers/additional_info.html.erb
<h3>Tells us a few more things about yourself</h3>

<%= render :partial => "additionalinfo" %>

app/views/travellers/edit.html.erb
<!-- Travellers#edit
Find me in app/views/travellers/edit.html.erb -->
<h3>Edit Traveller</h3>

<%= render :partial => "editform" %>

app/views/travellers/index.html.erb
<!-- Travellers#index
Find me in app/views/travellers/index.html.erb -->

<h3>Wine Travellers</h3>
<!-- <div class="formtext">
  <div class="formtext-background"></div>
<% @travellers.each do |t| %>
<p>   <%= cl_image_tag( t.image, :class => "img-circle" ) %>
  <%= link_to( t.first_name, t ) %> <%= link_to( t.last_name, t ) %>
</p>
<% end %>

<div class="waves-effect waves-light btn"><%= link_to "New Traveller", new_traveller_path %></div>

</div> -->

<div class="formtext">
  <div class="formtext-background"></div>
  <% @travellers.each do |t| %>
    <ul class="collection">
      <li class="collection-item avatar brown lighten-3">
         <%= cl_image_tag( t.image, :alt => "", :class => "circle" ) %>
         <span class="title"><%= link_to( t.first_name, t ) %> <%= link_to( t.last_name, t ) %></span>
         <p> Favorite winery: <%= t.fav_winery %> <br>
             Favorite wine region: <%= t.fav_region %>
         </p>
         <!-- <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a> -->
      </li>
   </ul>
 <% end %>

<div class="waves-effect waves-light btn"><%= link_to "New Traveller", new_traveller_path %></div>

</div>

app/views/travellers/landing.html.erb
<h1>Travellers#landing</h1>
<p>Find me in app/views/travellers/landing.html.erb</p>

app/views/travellers/new.html.erb
<!-- Travellers#new
Find me in app/views/travellers/new.html.erb -->

<h3>Sign Up</h3>

<%= render :partial => "form" %>

app/views/travellers/search.html.erb
<h3>Search Wineries Near You</h3>


<form action="/travellers/search_results" method="GET">

<p>
  <label>What does your trip start?</label>
  <input type="text" placeholder="Enter your location" name="question">
</p>

<input type="submit" value="Find wineries near me: ">

</form>

app/views/travellers/search_results.html.erb
<h3>Select a winery from the list above</h3>

<!-- Enter list of wineries near the location entered... -->
<!-- <p>  My dear, the answer to your question  <span><%= @question %></span>  is: </p>
<p><span><%= @answer %></span></p> -->
<p>Show list of wineries near you</p>
<!--sort them by distance and time travel  ; have a select item next to the winery for planner-->




<p>Wine trip planner button</p>

app/views/travellers/show.html.erb
<!-- Travellers#show
Find me in app/views/travellers/show.html.erb -->

<h3><%= @traveller.first_name %>'s Profile</h3>
<div class="formtext">
  <div class="formtext-background"></div>
<h5>A few things about myself</h5>
<ul>
  <li><%= cl_image_tag( @traveller.image, :class => "thumbnail" ) %></li>
  <li>"Who am I? <%= "#{@traveller.first_name} #{@traveller.last_name}" %></li>
  <li>"I live in <%= @traveller.city %>, <%= @traveller.country %>"</li>
  <!-- <li>"I'm kid of old, born in <%= @traveller.dob %>, so I can drink alright!"</li> -->
  <li>"Want to get in touch? You can reach me on <%= @traveller.email %>"</li>
</ul>

<h5>My favorite wine bits</h5>
<ul>
  <li>My favorite winery is <%= @traveller.fav_winery %></li>
  <li>My favorite wine region is <%= @traveller.fav_region %></li>
  <li>My favorite wine variety is <%= @traveller.fav_variety %></li>
</ul>

<!-- Only show these buttons if the @user vriable contains the same user as @current_user  >> otherwise others can delete others accounts -->
<% if @traveller == @current_traveller %>
<div class="controls">
  <%= link_to "Edit Traveller", edit_traveller_path( @traveller ) %> |
  <%= link_to "Delete Account", traveller_path( @traveller ), :method => :delete, :data => { :confirm => "Are you sure?" } %>
</div>
<% end %>
</div>