config/routes.rb
Rails.application.routes.draw do

  get 'directions/index'

  get 'directions/show'

  get 'directions/new'

  get 'directions/create'

  get 'directions/update'

  get 'directions/destroy'

  get 'regions/index'

  get 'regions/show'

  get 'regions/new'

  get 'regions/edit'

  get 'regions/search'

  get 'regions/search_result'

  get 'wineries/index'

  get 'wineries/show'

  get 'wineries/new'

  get 'wineries/edit'

  get 'wineries/search'

  get 'wineries/search_results'

  get 'wineries/index'

  get 'wineries/show'

  get 'wineries/new'

  get 'wineries/edit'

  # get 'wineries/search'

  # get 'wineries/search_results'

  root "pages#home"
  get "/home" => "pages#home"
  get "/about" => "pages#about"

  get "/wineries/searches" => "wineries#searches", :as => "search_wine"
  get "/wineries/search" => "wineries#search", :as => "search_wineries"
  get "/regions/search" => "regions#search", :as => "search_regions"
  get "/regions/search" => "region#search", :as => "search_region"
  get "/travellers/search_results" => "travellers#search_results", :as => "search_traveller"
  get "/travellers/additional_info" => "travellers#additional_info", :as => "additional_info_traveller"
  get "/travellers/edit" => "travellers#edit", :as => "edit_traveller"
  resources :travellers, :except =>[:edit]
  #Creates the CRUD urls for me (but ignoring EDIT)

  resources :wineries, :regions
  # this will allow you to have links and paths to wineries and regions

  get "/login" => "session#new", :as => "login"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"


end

app/models/winery.rb
# == Schema Information
#
# Table name: wineries
#
#  id                 :integer          not null, primary key
#  name               :text
#  winery_image       :text
#  winery_admin       :boolean          default(FALSE)
#  is_winery          :boolean
#  is_certified       :boolean
#  rating             :text
#  email              :text
#  website            :text
#  winery_lat         :float
#  winery_long        :float
#  feature_wine       :text
#  winery_description :text
#  winery_pitch       :text
#  must_try_wines     :text
#  winery_event       :text
#  winery_event_date  :date
#  visit_app_only     :boolean
#  cellar_door        :boolean
#  restaurant         :boolean
#  rest_name          :text
#  open_time_cd       :datetime
#  close_time_cd      :datetime
#  open_days_cd       :text
#  open_time_rest     :datetime
#  close_time_rest    :datetime
#  open_days_rest     :text
#  region_id          :integer
#  winery_location    :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Winery < ActiveRecord::Base
  has_and_belongs_to_many :travellers
  belongs_to :region
  geocoded_by :winery_location, :latitude  => :winery_lat, :longitude => :winery_long # ActiveRecord
  after_validation :geocode
end

app/controllers/wineries_controller.rb
class WineriesController < ApplicationController

  def index
    @wineries = Winery.all
  end

  def show
    @winery = Winery.find_by :id => params[:id]
  end

  def new
    @winery = Winery.new
  end

  def create
    @winery = Winery.new winery_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @winery.winery_image = req['public_id']
    end
    redirect_to winery_path ( @winery )
  end

  def edit
    @winery = Winery.find_by :id => params[:id]
  end

  def update
    @winery = Winery.find_by :id => params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @winery.winery_image = req['public_id']
    end
     @winery.assign_attributes( winery_params )
    if @winery.save
      redirect_to @winery
     else
        render :edit
    end
  end

    def destroy
      winery = Winery.find_by :id => params[:id]
      winery.destroy
      redirect_to wineries_path()
    end

    def search
      @wineries = Winery.all
      redirect_to wineries_search_results_path
    end

    def search_results
      @wineries = Winery.all
      @winery = Winery.find_by :id => params[:id]

    end
    # def searches
    #   @start = Winery.find_by(id: params[:start])
    #   @end = Winery.find_by(id: params[:end])
    #
    #   if @start && @end
    #     flash[:success] =
    #    "The distance between <b>#{@start.name}</b> and <b>#{@end.name}</b> is about #{@start.distance_from(@end.to_coordinates).round} km by helicopter."
    #  end
    #   redirect_to wineries_search_results_path
    # end


    private
      def winery_params
        params.require(:winery).permit(:email, :website, :name, :winery_image, :winery_location, :winery_pitch, :winery_description, :cellar_door, :restaurant, :must_try_wines)
      end
  end

  #
  # def search_results
  # end

app/helpers/wineries_helper.rb
module WineriesHelper
end

app/views/wineries/_wineryform.html.erb
<% unless @winery.errors.full_messages.empty? %>
<ul>
  <!-- Every error message printed out as a list item -->
  <%= @winery.errors.full_messages.each do |error| %>
  <li>
    <%= error %>
  </li>
 <% end %>
</ul>
<% end %>
<div class="formtext">
  <div class="formtext-background"></div>
<%= form_for(@winery, :html => {:multipart => true}) do |f| %>

<p>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>
</p>

<p>
  <%= f.label :winery_image %>
  <%= f.cl_image_upload :winery_image, :required => true %>
</p>

<p>
  <%= f.label :winery_pitch %>
  <%= f.text_field :winery_pitch, :required => true %>
</p>

<p>
  <%= f.label :must_try_wines %>
  <%= f.text_field :must_try_wines, :required => true %>
</p>

<p>
  <%= f.check_box :cellar_door, :required => true %>
  <%= f.label :cellar_door %>
</p>

<p>
  <%= f.check_box :restaurant, :required => true %>
  <%= f.label :restaurant %>
</p>

<p>
  <%= f.label :winery_location %>
  <%= f.text_field :winery_location, :required => true %>
</p>

<p>
  <%= f.label :website %>
  <%= f.url_field :website, :required => true %>
</p>

<p>
  <%= f.label :email %>
  <%= f.email_field :email, :required => true %>
</p>

<%= f.submit %>
<% end %>
</div>
</div>

app/views/wineries/edit.html.erb
<!-- <h1>Wineries#edit</h1>
<p>Find me in app/views/wineries/edit.html.erb</p> -->

<h3>Edit Winery</h3>

<%= render :partial => "wineryform" %>

app/views/wineries/index.html.erb
<!-- <h1>Wineries#index</h1>
<p>Find me in app/views/wineries/index.html.erb</p> -->

<!-- <% @wineries.each do |w| %>
<div class="row">
     <div class="col s12 m3">
       <div class="card blue-grey darken-1">
         <div class="card-content white-text">
           <span class="card-title"><%= w.name %></span>
           <p><%= truncate(w.winery_pitch) %></p>
         </div>
         <div class="card-action">
           <%= link_to("More Details", winery_path(w) ) %> -->
<!-- <a href="http://www.google.com">Website</a> -->
<!-- <a href="#">This is a link</a> -->
<!-- </div>
       </div>
     </div>
    <% end %>
   </div>
<%= link_to "New Winery", new_winery_path %> -->
<!-- <div id="search-map">
 <i class="material-icons">search</i><div class="waves-effect waves-light btn"><%= link_to "Search", search_wineries_path %></div>
</div> -->
<div class="nav-wrapper">
      <form>
        <div class="input-field">
          <input id="search" type="search" required>
          <label for="search"><i class="material-icons">search</i></label>
          <i class="material-icons">close</i>
        </div>
      </form>
    </div>
<!-- <a class="btn-floating btn-large waves-effect waves-light green"><i class="material-icons">search</i></a> -->
<div class="row">
    <% @wineries.each do |w| %>
          <div class="col s12 m3">
              <div class="card">
                  <div class="card-image small">
                      <div class="materialboxed">
                          <%= cl_image_tag(w.winery_image, :gravity => "auto", :crop => "fill") %>
                    <!-- <span class="card-title"><%= w.name %></span> -->
                      </div>
                <!-- <div class="card-content">
              <p><%= truncate(w.winery_pitch) %></p>
            </div> -->
                  </div>
                  <div class="card-action brown lighten-5">
                      <%= link_to(w.name, winery_path(w) ) %>
                <!-- <a href="#">This is a link</a> -->
                  </div>
              </div>
          </div>
    <% end %>
</div>
    <div class="waves-effect waves-light btn"><%= link_to "New Winery", new_winery_path %></div>

app/views/wineries/new.html.erb
<!-- <h1>Wineries#new</h1>
<p>Find me in app/views/wineries/new.html.erb</p> -->

<h3>Create New Winery</h3>

<%= render :partial => "wineryform" %>

app/views/wineries/search.html.erb
<!-- <h1>Wineries#search</h1>
<p>Find me in app/views/wineries/search.html.erb</p> -->

<!--Creating an option for travellers to measure distance between 2 wineries  -->
<h3 class="display-4">Search</h3>

<div class="formtext">
  <div class="formtext-background"></div>
    <%= form_tag search_wine_path, :method => "get" do %>
      <fieldset class="form-group">
        <%= label_tag 'from', 'From' %>
        <%= select_tag 'from', options_from_collection_for_select(@wineries, :id, :name), class: "form-control" %>
      </fieldset>

      <fieldset class="form-group">
        <%= label_tag 'to', 'To' %>
        <%= select_tag 'to', options_from_collection_for_select(@wineries, :id, :name), class: "form-control" %>
      </fieldset>
      <br>
      <%= submit_tag 'Go!', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/wineries/search_results.html.erb
<h3 id="google_directions_region">Driving to wineries:</h3>
<!-- <p>Find me in app/views/wineries/search_results.html.erb</p> -->

    <div id="floating-panel">
        <strong>Start:</strong>
        <select id="start">
            <option value="sydney, new south wales">Sydney</option>
            <option value="melbourne, victoria">Melbourne</option>
            <option value="adelaide, south australia">Adelaide</option>
            <option value="canberra, new south wales">Canberra</option>
            <option value="hobart, tasmania">Hobart</option>
            <option value="perth, western australia">Perth</option>
            <option value="brisbane, queensland">Brisbane</option>
            <option value="sydney, new south wales">-----Wineries-----</option>
            <% @wineries.each do | w | %>
              <option value="<%= w.winery_location %>"><%= w.name %></option>
            <% end %>
            <!-- <option value="sydney, new south wales">Sydney</option>
            <option value="dickson, new south wales">Canberra District</option>
            <option value="cowra, new south wales">Cowra</option>
            <option value="gundagai, new south wales">Gundagai</option>
            <option value="port macquarie, new south wales">Hastings River</option>
            <option value="young, new south wales">Hilltops</option>
            <option value="pokolbin, new south wales">Hunter Valley</option>
            <option value="mudgee, new south wales">Mudgee</option>
            <option value="tenterfield, new south wales">New England</option>
            <option value="orange, new south wales">Orange</option>
            <option value="moama, new south wales">Perricoota</option>
            <option value="griffith, new south wales">Riverina</option>
            <option value="coolangatta, new south wales">Sholhaven Coast</option>
            <option value="mittagong, new south wales">Southern Highlands</option>
            <option value="tumbarumba, new south wales">Tumbarumba</option> -->
        </select>
        <br>
        <strong>End:</strong>
        <select id="end">
            <% @wineries.each do | w | %>
              <option value="<%= w.winery_location %>"><%= w.name %></option>
            <% end %>
            <!-- <option value="sydney, new south wales">Sydney</option>
            <option value="dickson, new south wales">Canberra District</option>
            <option value="cowra, new south wales">Cowra</option>
            <option value="gundagai, new south wales">Gundagai</option>
            <option value="port macquarie, new south wales">Hastings River</option>
            <option value="young, new south wales">Hilltops</option>
            <option value="pokolbin, new south wales">Hunter Valley</option>
            <option value="mudgee, new south wales">Mudgee</option>
            <option value="tenterfield, new south wales">New England</option>
            <option value="orange, new south wales">Orange</option>
            <option value="moama, new south wales">Perricoota</option>
            <option value="griffith, new south wales">Riverina</option>
            <option value="coolangatta, new south wales">Sholhaven Coast</option>
            <option value="mittagong, new south wales">Southern Highlands</option>
            <option value="tumbarumba, new south wales">Tumbarumba</option> -->
        </select>
      </div>
    <div id="right-panel"></div>
     <div id="map"></div>
    <script>
    function initMap() {
             var directionsDisplay = new google.maps.DirectionsRenderer;
             var directionsService = new google.maps.DirectionsService;
             var map = new google.maps.Map(document.getElementById('map'), {
               zoom: 7,
               center: {lat: -33.86, lng: 151.20}
             });
             directionsDisplay.setMap(map);
             directionsDisplay.setPanel(document.getElementById('right-panel'));

             var control = document.getElementById('floating-panel');
             control.style.display = 'block';
             map.controls[google.maps.ControlPosition.TOP_CENTER].push(control);

             var onChangeHandler = function() {
                console.log("ANAKNksn")
               calculateAndDisplayRoute(directionsService, directionsDisplay);
             };
             $(".select-wrapper input, select").on("change input", onChangeHandler);
            //  document.getElementById('start').addEventListener('change', onChangeHandler);
            //  document.getElementById('end').addEventListener('change', onChangeHandler);
           }

           function calculateAndDisplayRoute(directionsService, directionsDisplay) {
             var start = document.getElementById('start').value;
             var end = document.getElementById('end').value;
             directionsService.route({
               origin: start,
               destination: end,
               travelMode: 'DRIVING'
             }, function(response, status) {
               if (status === 'OK') {
                 directionsDisplay.setDirections(response);
               } else {
                 window.alert('Directions request failed due to ' + status);
               }
             });
           }

    </script>
    <script async defer
     src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB5qK_UhmrYD2Dbz1LTB9xx3upiU7Bmy2s&callback=initMap">
    </script>
    <!-- </div> -->

app/views/wineries/show.html.erb
<!-- Wineries#show
Find me in app/views/wineries/show.html.erb -->

 <div class="formtext">
   <div class="formtext-background"></div>
      <div class="row">
        <div class="col s12 m6 l4">
          <img id="winery-pic"><%= cl_image_tag( @winery.winery_image, :class => "thumbnail") %></img>
          <br>
        </div>
        <div class="col s12 m6 l8">
          <h3><%= @winery.name %></h3>
          <p> <%= @winery.winery_pitch %></p>
          <br>
        </div>
    </div>
</div>

<div class="formtext">
  <div class="formtext-background"></div>
     <div class="row">
     <div class="col s12 m4 l4">
       <br>
       <p class ="winery-stats">Winery rating:</p>
       <p class= "winery-output"> <%= @winery.rating %></p>
       <br>
       <p class ="winery-stats">Must try wines:</p>
       <p class= "winery-output"><%= @winery.must_try_wines %></p>
       <br>
       <p class ="winery-stats">Cellar door:</p>
       <p class= "winery-output"> <%= @winery.cellar_door %></p>
       <br>
       <p class ="winery-stats">Restaurant:</li>
       <p class= "winery-output"><%= @winery.restaurant %></p>
       <br>
       <p class ="winery-stats">Contact us:</p>
       <p class= "winery-output"><%= @winery.email %></p>
       <p class= "winery-output"><%= @winery.website %></p>
      <br>
       <p class ="winery-stats">Address:</p>
       <p class= "winery-output"><%= @winery.winery_location %></p>
       <br>
       <div class="controls">
         <%= link_to "Edit Winery", edit_winery_path( @winery ) %> |
         <%= link_to "Delete Winery", winery_path( @winery ), :method => :delete, :data => { :confirm => "Are you sure?" } %>
       </div>
    </div>

<div class="col s12 m8 l8">
  <div id="map-container">
    <div id="map-canvas" ></div>
  </div>

  <script>
     var winery = <%= raw @winery.to_json %>;

     function initMap() {

        var winery_map = {
           lat: winery["winery_lat"],
           lng: winery["winery_long"]
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'), {
           zoom: 7,
           center: winery_map
        });
        // var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';
        var marker = new google.maps.Marker({
           position: winery_map,
           map: map,
          // //  icon: iconBase + 'parking_lot_maps.png'
          // icon: iconBase + 'images/icon.jpg'
        });
      // asetting parameters for custom marker:
        function createImage(url){
          var image = {
            url: url,
            // This marker is 32 pixels wide by 32 pixels tall.
            size: new google.maps.Size(32, 32),
            // The origin for this image is 0,0.
            origin: new google.maps.Point(0,0),
            // The anchor for this image is the base of the flagpole at 0,32.
            anchor: new google.maps.Point(0, 32)
          };
          return image;
          }
        // creating a custom marker
        function createCustomMarker(position,map){
            marker = new google.maps.Marker({
            position: winery_map,
            map: map,
            icon: createImage("/assets/images/icon.png")
        });
      }

        function createInfoWindow(text){
          var infowindow = new google.maps.InfoWindow({
            content: text
          });
          return infowindow;
        }

      // add infowindow when clicking on the simple marker marker
      var info = createInfoWindow("<%= @winery.name %>");
      google.maps.event.addListener(marker, 'click', function() {
        info.open(map,marker);
      });


      var mapOptions = {
          center: new google.maps.LatLng(lat, long),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.NORMAL,
          panControl: true,
          zoomControlOptions: {
            style: google.maps.ZoomControlStyle.SMALL,
            position: google.maps.ControlPosition.LEFT_CENTER
          },
          mapTypeControlOptions: {
            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU,
            mapTypeIds: [google.maps.MapTypeId.ROADMAP, "map_style"]
          },
          scaleControl: false,
          streetViewControl: true,
          overviewMapControl: true
        };
//
//         private GoogleMap.OnMyLocationChangeListener myLocationChangeListener = new GoogleMap.OnMyLocationChangeListener() {
//     @Override
//     public void onMyLocationChange(Location location) {
//         LatLng loc = new LatLng(location.getLatitude(), location.getLongitude());
//         mMarker = mMap.addMarker(new MarkerOptions().position(loc));
//         if(mMap != null){
//             mMap.animateCamera(CameraUpdateFactory.newLatLngZoom(loc, 16.0f));
//         }
//     }
// };
// mMap.setOnMyLocationChangeListener(myLocationChangeListener);

   }
</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB5qK_UhmrYD2Dbz1LTB9xx3upiU7Bmy2s&callback=initMap">
</script>
<div id="driving-map">
 <div class="waves-effect waves-light btn"><i class="material-icons">navigation</i><%= link_to "    Driving Instructions", search_wineries_path %></div>
</div>
</div>
<!-- var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';
  var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    icon: iconBase + 'parking_lot_maps.png'
  }); -->