config/routes.rb
Rails.application.routes.draw do

  get 'directions/index'

  get 'directions/show'

  get 'directions/new'

  get 'directions/create'

  get 'directions/update'

  get 'directions/destroy'

  get 'regions/index'

  get 'regions/show'

  get 'regions/new'

  get 'regions/edit'

  get 'regions/search'

  get 'regions/search_result'

  get 'wineries/index'

  get 'wineries/show'

  get 'wineries/new'

  get 'wineries/edit'

  get 'wineries/search'

  get 'wineries/search_results'

  get 'wineries/index'

  get 'wineries/show'

  get 'wineries/new'

  get 'wineries/edit'

  # get 'wineries/search'

  # get 'wineries/search_results'

  root "pages#home"
  get "/home" => "pages#home"
  get "/about" => "pages#about"

  get "/wineries/searches" => "wineries#searches", :as => "search_wine"
  get "/wineries/search" => "wineries#search", :as => "search_wineries"
  get "/regions/search" => "regions#search", :as => "search_regions"
  get "/regions/search" => "region#search", :as => "search_region"
  get "/travellers/search_results" => "travellers#search_results", :as => "search_traveller"
  get "/travellers/additional_info" => "travellers#additional_info", :as => "additional_info_traveller"
  get "/travellers/edit" => "travellers#edit", :as => "edit_traveller"
  resources :travellers, :except =>[:edit]
  #Creates the CRUD urls for me (but ignoring EDIT)

  resources :wineries, :regions
  # this will allow you to have links and paths to wineries and regions

  get "/login" => "session#new", :as => "login"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"


end

app/models/region.rb
# == Schema Information
#
# Table name: regions
#
#  id                 :integer          not null, primary key
#  name               :text
#  location           :text
#  region_lat         :float
#  region_long        :float
#  vintages           :text
#  region_description :text
#  region_varieties   :text
#  region_img         :text
#  region_event       :text
#  region_event_date  :date
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Region < ActiveRecord::Base
  has_many :wineries
  has_many :travellers, :through => :wineries
  geocoded_by :location, :latitude  => :region_lat, :longitude => :region_long # ActiveRecord
  after_validation :geocode
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  def index
    @regions = Region.all
  end

  def show
    @region = Region.find_by :id => params[:id]
  end

  def new
    @region = Region.new
  end

  def create
    @region = Region.new region_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @region.region_img = req['public_id']
    end
    redirect_to region_path ( @region )
  end


  def edit
    @region = Region.find_by :id => params[:id]
  end

  def update
    @region = Region.find_by :id => params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @region.region_img = req['public_id']
    end
     @region.assign_attributes( region_params )
    if @region.save
      redirect_to @region
     else
        render :edit
    end
  end

    def destroy
      region = Region.find_by :id => params[:id]
      region.destroy
      redirect_to regions_path()
    end

    def search
      @regions = Region.all
      redirect_to regions_search_result_path
    end

    def search_result
      @regions = Region.all
      @region = Region.find_by :id => params[:id]

    end

    # def search
    #   @regions = Region.all
    #   redirect_to regions_search_result_path
    # end
    #
    # def search_results
    #   @regions = Region.all
    #   @region = Region.find_by :id => params[:id]
    # end


    private
      def region_params
        params.require(:region).permit(:name, :location, :vintages, :region_img, :region_description, :region_varieties, :region_event )
      end





  # def search
  # end
  #
  # def search_result
  # end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_regionform.html.erb
<% unless @region.errors.full_messages.empty? %>
<ul>
  <!-- Every error message printed out as a list item -->
  <%= @region.errors.full_messages.each do |error| %>
  <li>
    <%= error %>
  </li>
 <% end %>
</ul>
<% end %>

<div class="formtext">
  <div class="formtext-background"></div>
<%= form_for(@region, :html => {:multipart => true}) do |f| %>

<p>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>
</p>

<p>
  <%= f.label :region_img %>
  <%= f.cl_image_upload :region_img, :required => true %>
</p>

<p>
  <%= f.label :region_description %>
  <%= f.text_field :region_description, :required => true %>
</p>

<p>
  <%= f.label :region_varieties %>
  <%= f.text_field :region_varieties, :required => true %>
</p>

<p>
  <%= f.label :vintages %>
  <%= f.text_field :vintages, :required => true %>
</p>


<%= f.submit %>
<% end %>
</div>

app/views/regions/edit.html.erb
<!-- <h1>Regions#edit</h1>
<p>Find me in app/views/regions/edit.html.erb</p> -->

<h3>Edit Region</h3>

<%= render :partial => "regionform" %>

app/views/regions/index.html.erb
<!-- <h1>Regions#index</h1>
<p>Find me in app/views/regions/index.html.erb</p> -->

<div class="row">
  <% @regions.each do |r| %>
     <div class="col s12 m3">
           <div class="card">
                <div class="card-image small">
                      <div class="materialboxed">
                        <%= cl_image_tag(r.region_img, :gravity => "auto", :crop => "fill") %>
                      </div>
                </div>
            <div class="card-action brown lighten-5">
                <%= link_to(r.name, region_path(r) ) %>
            </div>
          </div>
    </div>
  <% end %>
</div>
<div class="waves-effect waves-light btn z-depth-5"><%= link_to "New Region", new_region_path %></div>



<!-- <! <script>
   var allRegions = <%= raw @regions.all.to_json %>;
   // var region = <%= raw @region.to_json %>;
   function initMap() {

      var all_regions = {
         lat: <%= Region.last.region_lat %>,
         lng: <%= Region.last.region_long %>
      };
      var map = new google.maps.Map(document.getElementById('map'), {
         zoom: 4,
         center: uluru
      });
      var marker = new google.maps.Marker({
         position: uluru,
         map: map
      });
   }
</script> -->


<!-- <script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB5qK_UhmrYD2Dbz1LTB9xx3upiU7Bmy2s&callback=initMap">
</script> -->
<!-- <script src="//maps.google.com/maps/api/js?key=AIzaSyAtDPs6dUK5euBiDG_6t-A1C9wG-ciR2so"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes --> -->

app/views/regions/new.html.erb
<!-- <h1>Regions#new</h1>
<p>Find me in app/views/regions/new.html.erb</p> -->

<h3>Create New Region</h3>

<%= render :partial => "regionform" %>

app/views/regions/search.html.erb
<h1>Regions#search</h1>
<p>Find me in app/views/regions/search.html.erb</p>

app/views/regions/search_result.html.erb
<h3 id="google_directions_region">Directions to wine regions:</h3>
<!-- <p>Find me in app/views/regions/search_result.html.erb</p> -->

    <div id="floating-panel">
        <strong>Start:</strong>
        <select id="start">
            <option value="sydney, new south wales">Sydney</option>
            <option value="melbourne, victoria">Melbourne</option>
            <option value="adelaide, south australia">Adelaide</option>
            <option value="canberra, new south wales">Canberra</option>
            <option value="hobart, tasmania">Hobart</option>
            <option value="perth, western australia">Perth</option>
            <option value="brisbane, queensland">Brisbane</option>
            <option value="sydney, new south wales" id="separator">---Wine Regions---</option>
            <% @regions.each do | r | %>
              <option value="<%= r.location %>"><%= r.name %></option>
                <%end %>

            <!-- <option value="sydney, new south wales">Sydney</option>
            <option value="dickson, new south wales">Canberra District</option>
            <option value="cowra, new south wales">Cowra</option>
            <option value="gundagai, new south wales">Gundagai</option>
            <option value="port macquarie, new south wales">Hastings River</option>
            <option value="young, new south wales">Hilltops</option>
            <option value="pokolbin, new south wales">Hunter Valley</option>
            <option value="mudgee, new south wales">Mudgee</option>
            <option value="tenterfield, new south wales">New England</option>
            <option value="orange, new south wales">Orange</option>
            <option value="moama, new south wales">Perricoota</option>
            <option value="griffith, new south wales">Riverina</option>
            <option value="coolangatta, new south wales">Sholhaven Coast</option>
            <option value="mittagong, new south wales">Southern Highlands</option>
            <option value="tumbarumba, new south wales">Tumbarumba</option> -->
        </select>
        <br>
        <strong>End:</strong>
        <select id="end">
            <% @regions.each do | r | %>
              <option value="<%= r.location %>"><%= r.name %></option>
            <% end %>
            <!-- <option value="sydney, new south wales">Sydney</option>
            <option value="dickson, new south wales">Canberra District</option>
            <option value="cowra, new south wales">Cowra</option>
            <option value="gundagai, new south wales">Gundagai</option>
            <option value="port macquarie, new south wales">Hastings River</option>
            <option value="young, new south wales">Hilltops</option>
            <option value="pokolbin, new south wales">Hunter Valley</option>
            <option value="mudgee, new south wales">Mudgee</option>
            <option value="tenterfield, new south wales">New England</option>
            <option value="orange, new south wales">Orange</option>
            <option value="moama, new south wales">Perricoota</option>
            <option value="griffith, new south wales">Riverina</option>
            <option value="coolangatta, new south wales">Sholhaven Coast</option>
            <option value="mittagong, new south wales">Southern Highlands</option>
            <option value="tumbarumba, new south wales">Tumbarumba</option> -->
        </select>
      </div>
    <div id="right-panel"></div>
     <div id="map"></div>
    <script>
    function initMap() {
             var directionsDisplay = new google.maps.DirectionsRenderer;
             var directionsService = new google.maps.DirectionsService;
             var map = new google.maps.Map(document.getElementById('map'), {
               zoom: 7,
               center: {lat: -33.86, lng: 151.20}
             });
             directionsDisplay.setMap(map);
             directionsDisplay.setPanel(document.getElementById('right-panel'));

             var control = document.getElementById('floating-panel');
             control.style.display = 'block';
             map.controls[google.maps.ControlPosition.TOP_CENTER].push(control);

             var onChangeHandler = function() {
                console.log("ANAKNksn")
               calculateAndDisplayRoute(directionsService, directionsDisplay);
             };
             $(".select-wrapper input, select").on("change input", onChangeHandler);
            //  document.getElementById('start').addEventListener('change', onChangeHandler);
            //  document.getElementById('end').addEventListener('change', onChangeHandler);
           }

           function calculateAndDisplayRoute(directionsService, directionsDisplay) {
             var start = document.getElementById('start').value;
             var end = document.getElementById('end').value;
             directionsService.route({
               origin: start,
               destination: end,
               travelMode: 'DRIVING'
             }, function(response, status) {
               if (status === 'OK') {
                 directionsDisplay.setDirections(response);
               } else {
                 window.alert('Directions request failed due to ' + status);
               }
             });
           }

    </script>
    <script async defer
     src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB5qK_UhmrYD2Dbz1LTB9xx3upiU7Bmy2s&callback=initMap">
    </script>
    <!-- </div> -->

    <!-- <option value="sydney, new south wales">Sydney</option>
    <option value="dickson, new south wales">Canberra District</option>
    <option value="cowra, new south wales">Cowra</option>
    <option value="gundagai, new south wales">Gundagai</option>
    <option value="port macquarie, new south wales">Hastings River</option>
    <option value="young, new south wales">Hilltops</option>
    <option value="pokolbin, new south wales">Hunter Valley</option>
    <option value="mudgee, new south wales">Mudgee</option>
    <option value="tenterfield, new south wales">New England</option>
    <option value="orange, new south wales">Orange</option>
    <option value="moama, new south wales">Perricoota</option>
    <option value="griffith, new south wales">Riverina</option>
    <option value="coolangatta, new south wales">Sholhaven Coast</option>
    <option value="mittagong, new south wales">Southern Highlands</option>
    <option value="tumbarumba, new south wales">Tumbarumba</option> -->

app/views/regions/show.html.erb
<!-- <h1>Regions#show</h1>
<p>Find me in app/views/regions/show.html.erb</p> -->

<div class="formtext">
  <div class="formtext-background"></div>
     <div class="row">
       <div class="col s12 m6 l4">
         <img id="region-pic"><%= cl_image_tag( @region.region_img, :class => "thumbnail") %></img>
         <br>
       </div>
       <div class="col s12 m6 l8">
         <h3><%= @region.name %></h3>
         <p> <%= @region.region_description %></p>
         <br>
       </div>
   </div>
</div>

<div class="formtext">
  <div class="formtext-background"></div>
     <div class="row">
       <div class="col s12 m4 l4">
         <br>
         <p class ="region-stats">Main varieties:</p>
         <p class= "region-output"><%= @region.region_varieties %></p>
         <br>
         <p class ="region-stats">Recent vintages:</p>
         <p class= "region-output"> <%= @region.vintages %></p>
         <br>
         <p class="region-stats"><%= @region.name %> wineries:</hp>
           <% @region.wineries.each do |w| %>
           <p class="wineriesinregion">
             <%= link_to( w.name, winery_path(w) ) %>
           </p>
           <% end %>
        <br>
         <p class ="region-stats">Location:</p>
         <p class= "region-output"><%= @region.location %></p>
         <br>
         <div class="controls">
           <%= link_to "Edit Region", edit_region_path( @region ) %> |
           <%= link_to "Delete Region", region_path( @region ), :method => :delete, :data => { :confirm => "Are you sure?" } %>
         </div>
      </div>

    <div class="col s12 m8 l8">
      <div id="map-container">
        <div id="map-canvas" ></div>
      </div>

        <script>
        var region = <%= raw @region.to_json %>;

        function initMap() {

           var region_map = {
              lat: region["region_lat"],
              lng: region["region_long"]
           };
           var map = new google.maps.Map(document.getElementById('map-canvas'), {
              zoom: 7,
              center: region_map
           });

           var marker = new google.maps.Marker({
              position: region_map,
              map: map,
             // //  icon: iconBase + 'parking_lot_maps.png'
             // icon: iconBase + 'images/icon.jpg'
           });
         // asetting parameters for custom marker:
           function createImage(url){
             var image = {
               url: url,
               // This marker is 32 pixels wide by 32 pixels tall.
               size: new google.maps.Size(32, 32),
               // The origin for this image is 0,0.
               origin: new google.maps.Point(0,0),
               // The anchor for this image is the base of the flagpole at 0,32.
               anchor: new google.maps.Point(0, 32)
             };
             return image;
             }
           // creating a custom marker
           function createCustomMarker(position,map){
               marker = new google.maps.Marker({
               position: region_map,
               map: map,
               icon: createImage("/assets/images/icon.png")
           });
         }

           function createInfoWindow(text){
             var infowindow = new google.maps.InfoWindow({
               content: text
             });
             return infowindow;
           }

         // add infowindow when clicking on the simple marker marker
         var info = createInfoWindow("<%= @region.name %>");
         google.maps.event.addListener(marker, 'click', function() {
           info.open(map,marker);
         });


         var mapOptions = {
             center: new google.maps.LatLng(lat, long),
             zoom: 8,
             mapTypeId: google.maps.MapTypeId.NORMAL,
             panControl: true,
             zoomControlOptions: {
               style: google.maps.ZoomControlStyle.SMALL,
               position: google.maps.ControlPosition.LEFT_CENTER
             },
             mapTypeControlOptions: {
               style: google.maps.MapTypeControlStyle.DROPDOWN_MENU,
               mapTypeIds: [google.maps.MapTypeId.ROADMAP, "map_style"]
             },
             scaleControl: false,
             streetViewControl: true,
             overviewMapControl: true
           };
        //
        //  var region_wineries = <%= raw @region.wineries.to_json %>;
         //
        //  function initMap() {
         //
        //     // var region_map = {
        //     //    lat: region["region_lat"],
        //     //    lng: region["region_long"]
        //     // };
        //     var region_map = {
        //        lat: -33,
        //        lng: 151
        //     };
         //
        //     var map = new google.maps.Map(document.getElementById('map-region'), {
        //        zoom: 7,
        //        center: region_map
        //     });

          //   setMarkers(map);
          //   var wineries = [
          //   <% @region.wineries.each do |w| %>
          //     [ w.name, w.winery_lat, w.winery_long],
          //   <% end %>
          //   ];
          //   <% @region.wineries.each do |w| %>
          //     var winery
          //   var winery = new google.maps.Marker({
          //      position: winery_map,
          //      map: map,
          // <% end %>
          //
          // function setMarkers(map) {
          //
          // // asetting parameters for custom marker:
          //   function createImage(url){
          //     var image = {
          //       url: url,
          //       // This marker is 32 pixels wide by 32 pixels tall.
          //       size: new google.maps.Size(32, 32),
          //       // The origin for this image is 0,0.
          //       origin: new google.maps.Point(0,0),
          //       // The anchor for this image is the base of the flagpole at 0,32.
          //       anchor: new google.maps.Point(0, 32)
          //     };
          //     return image;
          //     }
          //
          //
          //   // creating a custom marker
          //
          //
          //
          //   function createCustomMarker(position,map){
          //       marker = new google.maps.Marker({
          //       position: region_map,
          //       map: map,
          //       icon: createImage("/assets/images/icon.png")
          //   });
          // }
          //
          //   function createInfoWindow(text){
          //     var infowindow = new google.maps.InfoWindow({
          //       content: text
          //     });
          //     return infowindow;
          //   }
          //
          // // add infowindow when clicking on the simple marker marker
          // var info = createInfoWindow("<%= @region.wineries.name %>");
          // google.maps.event.addListener(marker, 'click', function() {
          //   info.open(map,marker);
          // });
          //
          //
          // var mapOptions = {
          //     center: new google.maps.LatLng(lat, long),
          //     zoom: 8,
          //     mapTypeId: google.maps.MapTypeId.NORMAL,
          //     panControl: true,
          //     zoomControlOptions: {
          //       style: google.maps.ZoomControlStyle.SMALL,
          //       position: google.maps.ControlPosition.LEFT_CENTER
          //     },
          //     mapTypeControlOptions: {
          //       style: google.maps.MapTypeControlStyle.DROPDOWN_MENU,
          //       mapTypeIds: [google.maps.MapTypeId.ROADMAP, "map_style"]
          //     },
          //     scaleControl: false,
          //     streetViewControl: true,
          //     overviewMapControl: true
          //   };
      //
      //         private GoogleMap.OnMyLocationChangeListener myLocationChangeListener = new GoogleMap.OnMyLocationChangeListener() {
      //     @Override
      //     public void onMyLocationChange(Location location) {
      //         LatLng loc = new LatLng(location.getLatitude(), location.getLongitude());
      //         mMarker = mMap.addMarker(new MarkerOptions().position(loc));
      //         if(mMap != null){
      //             mMap.animateCamera(CameraUpdateFactory.newLatLngZoom(loc, 16.0f));
      //         }
      //     }
      // };
      // mMap.setOnMyLocationChangeListener(myLocationChangeListener);

       }
      </script>
      <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB5qK_UhmrYD2Dbz1LTB9xx3upiU7Bmy2s&callback=initMap">
      </script>
      <div id="driving-map">
      <div class="waves-effect waves-light btn"><i class="material-icons">navigation</i><%= link_to "    Driving Instructions", search_regions_path %></div>
      </div>
      </div>
      <!-- var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';
      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        icon: iconBase + 'parking_lot_maps.png'
      }); -->