config/routes.rb
Rails.application.routes.draw do

  get 'directions/index'

  get 'directions/show'

  get 'directions/new'

  get 'directions/create'

  get 'directions/update'

  get 'directions/destroy'

  get 'regions/index'

  get 'regions/show'

  get 'regions/new'

  get 'regions/edit'

  get 'regions/search'

  get 'regions/search_result'

  get 'wineries/index'

  get 'wineries/show'

  get 'wineries/new'

  get 'wineries/edit'

  get 'wineries/search'

  get 'wineries/search_results'

  get 'wineries/index'

  get 'wineries/show'

  get 'wineries/new'

  get 'wineries/edit'

  # get 'wineries/search'

  # get 'wineries/search_results'

  root "pages#home"
  get "/home" => "pages#home"
  get "/about" => "pages#about"

  get "/wineries/searches" => "wineries#searches", :as => "search_wine"
  get "/wineries/search" => "wineries#search", :as => "search_wineries"
  get "/regions/search" => "regions#search", :as => "search_regions"
  get "/regions/search" => "region#search", :as => "search_region"
  get "/travellers/search_results" => "travellers#search_results", :as => "search_traveller"
  get "/travellers/additional_info" => "travellers#additional_info", :as => "additional_info_traveller"
  get "/travellers/edit" => "travellers#edit", :as => "edit_traveller"
  resources :travellers, :except =>[:edit]
  #Creates the CRUD urls for me (but ignoring EDIT)

  resources :wineries, :regions
  # this will allow you to have links and paths to wineries and regions

  get "/login" => "session#new", :as => "login"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WineryTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Karla" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="nav-extended">
      <div class="nav-wrapper">
        <a href="#" class="brand-logo">  Winery Tracker</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", "/about" %></li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", "/about" %></li>
        </ul>

        <ul class="tabs tabs-transparent">
          <li class="tab"><%= link_to "Wineries", wineries_path, :target => "_self" %></li>
          <li class="tab"><%= link_to "Wine Regions", regions_path, :target => "_self" %></li>
          <li class="tab"><%= link_to "Travellers", travellers_path, :target => "_self" %></li>
          <li class="tab"><%= link_to "Search by Winery", search_wineries_path, :target => "_self" %></li>
          <!-- <li class="tab"><%= link_to "Search by Region", search_regions_path, :target => "_self" %></li> -->
          <% unless @current_traveller.present? %>
          <li class="tab"><%= link_to "Sign Up", new_traveller_path, :target => "_self" %></li>
          <li class="tab"><%= link_to "Log In", login_path, :target => "_self" %></li>
          <% else %>
          <li class="tab"><%= link_to "Log Out", login_path, :target => "_self", :method => :delete %></li>
          <% end %>
        </ul>
      </div>
    </nav>
<!-- use <main> and </main> to keep the footer on the bottom of page..see scss with main styling -->
<main>
<br>
<div class="container">
<%= yield %>
</div>
<br>
</main>
<footer class="page-footer brown darken-1">
         <!-- <div class="container">
          <div class="row">
            <div class="col l6 s12">
              <h5 class="white-text">Footer Content</h5>
              <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>  -->
            <!-- </div> -->
            <!-- <div class="col l4 offset-l2 s12">
              <h5 class="white-text">Links</h5>
              <ul> -->
                <!-- <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li> -->
              <!-- </ul>
            </div>
          </div>
        </div> -->
        <div class="footer-copyright brown darken-2">
          <div class="container">
          © 2017 The Barrel Hunter Productions
          <a class="grey-text text-lighten-4 right" href="http://www.instagram.com/thebarrelhunter/">Follow us on Instagram</a>
          </div>
        </div>
      </footer>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'  %>
</body>
</html>